version: "1"
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: directus
      POSTGRES_PASSWORD: directus
      POSTGRES_DB: directus
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready", "--host=localhost", "--username=directus"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_interval: 5s
      start_period: 30s
  directus:
    image: directus/directus:11.1.2
    ports:
      - 8055:8055
    volumes:
      - ./test-extension:/directus/extensions/test-extension
    depends_on:
      db:
        condition: service_healthy
    environment:
      SECRET: "replace-with-secure-random-value"

      ADMIN_EMAIL: "admin@example.com"
      ADMIN_PASSWORD: "d1r3ctu5"

      DB_CLIENT: "pg"
      DB_HOST: "db"
      DB_PORT: "5432"
      DB_DATABASE: "directus"
      DB_USER: "directus"
      DB_PASSWORD: "directus"
      WEBSOCKETS_ENABLED: "true"